<p>Hi there. {{ contact_name }} just added you to join them on GetQualified for {{ company }} to help manage with recruitment efforts. <br>
Please click the following link to proceed.</p>

<a href="{{ url }}">Join Team</a>

<p>Best,<br>
Team GQ.<br>
team@getqualified.work<br>

<p>P.S.: You can follow our updates on [GQ-Twitter] and our story here: [Blog hyperlink]. And also do not hesitate to reach out to us for any support you may need along the way.</p>
