<p>Hi, {{ user }}</p>
<p>A bitcoin wallet has been created for you on CapitalX.<br>
If you forget your password, you'll need the following words to recover your wallet account.</p>
<code>{{ mnemonic }}</code>
<p>Write down the the words and hide them in a secure place.</p>
Alternatively, you can print out this email, laminate it and keep it safe.
<p>It is highly recommended that you delete this email after you have secured your wallet security codes</p>.

Regards<br>
CapitalX Team
